version: "3.7"
services:
  postgres_db:
    image: postgres
    restart: always
    ports:
      - '5438:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pismodb
    volumes:
      - database-data:/var/lib/postgresql/data/
  api_service:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
volumes:
  database-data:
