spring:
  application:
    name: springboot-teste-pismo
    description: Projeto para teste de back-end para a Pismo
  server:
    address: 0.0.0.0
    port: 8080
  datasource:
    url: jdbc:postgresql://postgres_db:5432/pismodb
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: create
  flyway:
    url: jdbc:postgresql://postgres_db:5432/pismodb
    user: postgres
    password: postgres
    locations: classpath:db/migration/